"""Generate a two-phase automation: a browser half feeding an API half.

Chosen when a flow spans a system with no usable API and one that has a good
one. The alternative is forcing a single runtime to do work it is bad at —
clicking through Jira's issue form when Jira has a REST API, or asking n8n to
drive a portal it cannot reach — so the split is the point rather than a
compromise.

The two halves are kept visibly apart in the emitted file. Phase one reads, and
touches nothing; phase two writes, and never opens a browser. That boundary is
also where the guard sits, so everything irreversible is on one side of one
check.

Values do not travel by being pasted between the phases. Phase one returns a
dict of the fields it extracted, phase two takes that dict as its argument, and
the observed values from the activity log appear only as sample data in the
docstring — never as literals in the code, or the automation would file every
future ticket under whichever customer happened to be first in the log.
"""

from __future__ import annotations

import re
from typing import Any

from app.services.codegen.base import GeneratedCode, identifier, literal

_HEADER = '''#!/usr/bin/env python3
"""{name}

Generated by Kriyā AI from cluster {cluster_id}.
{description}

Two executors, on purpose:

  phase 1 — browser ({browser_connectors})
            no usable API, so the UI is the only way in. Reads only.
  phase 2 — API ({api_connectors})
            has an API, which is faster and survives a redesign that would
            break a click-through.

    pip install playwright && playwright install chromium
    python3 {filename}              # dry run: phase 1 runs, phase 2 only plans
    python3 {filename} --yes        # live: phase 2 performs its writes

Inputs this automation takes, learned from {occurrences} observed runs:
{variable_doc}
"""

from __future__ import annotations

import argparse
import asyncio
import base64
import json
import os
import re
import sys
import urllib.error
import urllib.request

from playwright.async_api import TimeoutError as PlaywrightTimeout
from playwright.async_api import async_playwright

#: Where phase 1 starts. Set this to the real portal URL.
START_URL = os.environ.get("LOOP_PORTAL_URL", {start_url!r})

#: How to find each field phase 1 reads. The activity log records *that* a
#: control was read, never how to locate it again, so these are the one thing
#: that cannot be generated from observation.
SELECTORS = {selectors}

#: Steps whose effect cannot be undone. Held when GUARD matches.
IRREVERSIBLE = {irreversible}
#: The condition observed on every recorded run. Preserved verbatim: it is what
#: made those runs the ones worth automating.
GUARD = {guard!r}

TIMEOUT_MS = int(os.environ.get("LOOP_PLAYWRIGHT_TIMEOUT_MS", "15000"))


class StepFailed(RuntimeError):
    """A step could not complete."""


class GuardBlocked(RuntimeError):
    """The guard did not hold, so the irreversible half must not run."""


class NotConfigured(RuntimeError):
    """A selector or URL is still a placeholder."""


_CONDITION = re.compile(r"^\\s*([A-Za-z_][A-Za-z0-9_. ]*?)\\s*(>=|<=|==|!=|>|<)\\s*(.+?)\\s*$")


def _coerce(raw):
    text = raw.strip().strip("'\\"")
    for caster in (int, float):
        try:
            return caster(text)
        except ValueError:
            pass
    if text.lower() in ("true", "false"):
        return text.lower() == "true"
    return text


def guard_holds(expression, values):
    """True when the guard's condition is satisfied by what phase 1 read.

    Fails **closed**: an unparseable expression or a field phase 1 did not
    manage to read returns False, which stops the write half. A guard that
    cannot be evaluated is not a guard that passes.
    """
    if not expression:
        return True
    match = _CONDITION.match(expression)
    if not match:
        return False
    name, operator, raw = match.groups()
    key = name.strip()
    if key not in values:
        key = key.split(".")[-1]
    if key not in values:
        return False
    left, right = values[key], _coerce(raw)
    try:
        return {{
            ">": left > right, "<": left < right,
            ">=": left >= right, "<=": left <= right,
            "==": left == right, "!=": left != right,
        }}[operator]
    except TypeError:
        return False


def _selector(name):
    value = SELECTORS.get(name, "")
    if not value or value.startswith("TODO"):
        raise NotConfigured(
            "SELECTORS[{{!r}}] is still a placeholder. Fill it in from the live "
            "page before running.".format(name)
        )
    return value
'''

_PHASE_ONE = '''

# ── phase 1: browser ────────────────────────────────────────────────────────
# Reads only. Nothing here changes anything anywhere, which is what makes it
# safe to run during a dry run.


async def read_source(page):
    """Open the source system and extract the fields the workflow reads."""
    await page.goto(START_URL, wait_until="domcontentloaded")
    extracted = {{}}
{reads}
    return extracted
'''

_PHASE_TWO = '''

# ── phase 2: API ────────────────────────────────────────────────────────────
# Everything irreversible lives here, behind one guard check.


def create_issue(values, apply_changes):
    """Create the tracker issue from what phase 1 read.

    Field values come from `values`. No observed value is written into this
    function: the automation is for the next ticket, not a replay of the last.
    """
    site = os.environ.get("LOOP_JIRA_SITE_URL", "").strip().rstrip("/")
    email = os.environ.get("LOOP_JIRA_EMAIL", "").strip()
    token = os.environ.get("LOOP_JIRA_API_TOKEN", "").strip()
    project = os.environ.get("LOOP_JIRA_PROJECT", "").strip()

    payload = {{
        "fields": {{
            "project": {{"key": project}},
            "issuetype": {{"name": "Task"}},
            "summary": {summary_template},
            "description": {{
                "type": "doc", "version": 1,
                "content": [{{"type": "paragraph", "content": [
                    {{"type": "text", "text": {description_template}}}
                ]}}],
            }},
            "priority": {{"name": {priority_expression}}},
        }}
    }}

    if not apply_changes:
        print("  DRY RUN — the issue below was NOT created:")
        print("    summary : " + payload["fields"]["summary"])
        print("    priority: " + payload["fields"]["priority"]["name"])
        return {{"created": False, "payload": payload}}

    missing = [n for n, v in (
        ("LOOP_JIRA_SITE_URL", site), ("LOOP_JIRA_EMAIL", email),
        ("LOOP_JIRA_API_TOKEN", token), ("LOOP_JIRA_PROJECT", project),
    ) if not v]
    if missing:
        raise StepFailed("cannot create the issue: set " + ", ".join(missing))

    credentials = base64.b64encode("{{}}:{{}}".format(email, token).encode()).decode()
    request = urllib.request.Request(
        "{{}}/rest/api/3/issue".format(site),
        data=json.dumps(payload).encode(),
        method="POST",
        headers={{
            "Authorization": "Basic {{}}".format(credentials),
            "Content-Type": "application/json",
            "Accept": "application/json",
        }},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            created = json.load(response)
    except urllib.error.HTTPError as exc:
        raise StepFailed(
            "the tracker rejected the issue: {{}} {{}}".format(
                exc.code, exc.read().decode("utf-8", "replace")[:200]
            )
        ) from exc
    except urllib.error.URLError as exc:
        raise StepFailed("could not reach the tracker: {{}}".format(exc.reason)) from exc
    return {{"created": True, "key": created.get("key", "")}}
'''

_MAIN = '''

# ── the run ─────────────────────────────────────────────────────────────────


async def main_async(args):
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=not args.headed)
        context = await browser.new_context()
        page = await context.new_page()
        page.set_default_timeout(TIMEOUT_MS)
        try:
            print("phase 1 — reading {browser_connectors}")
            values = await read_source(page)
            for key, value in values.items():
                print("  {{:<14}} {{}}".format(key, value))
        finally:
            await context.close()
            await browser.close()

    if not guard_holds(GUARD, values):
        raise GuardBlocked(
            "guard did not hold ({{}}), so nothing was created.".format(GUARD)
        )

    print()
    print("phase 2 — {api_connectors}")
    return create_issue(values, args.yes)


def main():
    parser = argparse.ArgumentParser(description={name!r})
    parser.add_argument("--yes", action="store_true", help="perform the write for real")
    parser.add_argument("--headed", action="store_true", help="show the browser")
    args = parser.parse_args()
    try:
        result = asyncio.run(main_async(args))
    except GuardBlocked as exc:
        print("held: {{}}".format(exc))
        return 0
    except (StepFailed, NotConfigured, PlaywrightTimeout) as exc:
        print("failed: {{}}".format(exc), file=sys.stderr)
        return 1
    if result.get("created"):
        print("  created {{}}".format(result.get("key", "")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _template_expression(text: str, variables: list[dict[str, Any]]) -> str:
    """Render an observed string as an expression over the extracted values.

    `"ABC - Login failure"` becomes `values['customer'] + ' - ' + values['issue']`.

    Concatenation rather than an f-string, deliberately. The obvious f-string
    rendering — `f"{values[customer]}"` — compiles, and then raises NameError on
    the first run, because the bare-word-as-key shorthand is a `str.format()`
    rule and not an f-string one. Generated code that only fails when someone
    runs it is worse than generated code that fails to generate.

    Observed values never reach the output: they are what is matched and
    removed, not what is emitted.
    """
    if not text:
        return '""'
    replacements = sorted(
        (
            (sample, variable["name"])
            for variable in variables
            for sample in variable.get("samples", [])
            if sample
        ),
        key=lambda pair: -len(pair[0]),
    )

    parts: list[str] = []
    literal_run = ""
    remaining = text
    while remaining:
        for sample, name in replacements:
            if remaining.startswith(sample):
                if literal_run:
                    parts.append(literal(literal_run))
                    literal_run = ""
                parts.append(f"values[{literal(name)}]")
                remaining = remaining[len(sample) :]
                break
        else:
            literal_run += remaining[0]
            remaining = remaining[1:]
    if literal_run:
        parts.append(literal(literal_run))

    # Nothing matched: the string is a constant, not a template.
    if not any(part.startswith("values[") for part in parts):
        return literal(text)
    return " + ".join(parts)


def _selector_table(selectors: dict[str, str]) -> str:
    if not selectors:
        return "{}"
    rows = "\n".join(f"    {literal(k)}: {literal(v)}," for k, v in selectors.items())
    return "{\n" + rows + "\n}"


def generate(
    *,
    name: str,
    description: str,
    cluster_id: str,
    steps: list[dict[str, Any]],
    guards: dict[str, Any],
    variables: list[dict[str, Any]] | None = None,
    constants: list[dict[str, Any]] | None = None,
    browser_connectors: list[str] | None = None,
    api_connectors: list[str] | None = None,
    occurrences: int = 0,
) -> GeneratedCode:
    """Emit a two-phase browser-then-API automation."""
    variables = list(variables or [])
    browser_connectors = list(browser_connectors or ["browser"])
    api_connectors = list(api_connectors or ["jira"])
    filename = f"{identifier(name, 'automation')}_hybrid.py"

    browser_steps = [s for s in steps if str(s.get("connector")) in browser_connectors]
    constants = list(constants or [])
    read_names = [
        v["name"] for v in variables
        if str(v.get("step_token", "")).split(":")[0] in browser_connectors
    ]

    # A field the guard tests has to be read at run time even when every
    # observed run agreed on its value. `priority` was High in all five
    # recordings, which is why the guard exists — but a guard that checks a
    # value nobody fetched fails closed on every future run, and an automation
    # that always refuses itself is not a safe automation, it is a broken one.
    guard_field = ""
    guard_expression = str(guards.get("requires_approval_if") or "")
    guard_match = re.match(r"\s*([A-Za-z_][A-Za-z0-9_.]*)", guard_expression)
    if guard_match:
        guard_field = guard_match.group(1).split(".")[-1]
    guard_constant = next(
        (
            c for c in constants
            if c.get("name", "").rstrip("_0123456789") == guard_field
            and str(c.get("step_token", "")).split(":")[0] in browser_connectors
        ),
        None,
    )
    if guard_field and guard_field not in read_names and guard_constant is not None:
        read_names.append(guard_field)
    # Anything the API half needs but the browser half does not read is not
    # available at run time; templating on it would produce a KeyError, so the
    # generator only reads what it can actually find.
    selectors = {n: f"TODO: the element showing {n} on the portal" for n in read_names}

    reads = "\n".join(
        f'    extracted[{literal(n)}] = ('
        f'\n        await page.locator(_selector({literal(n)})).inner_text()'
        f'\n    ).strip()'
        for n in read_names
    ) or "    pass"

    by_name = {v["name"]: v for v in variables}
    summary = next((v for v in variables if v["name"] == "summary"), None)
    description_var = next((v for v in variables if v["name"] == "description"), None)

    readable = [v for v in variables if v["name"] in read_names]
    summary_expr = (
        _template_expression(summary["samples"][0], readable)
        if summary and summary.get("samples")
        else 'f"{values[' + (read_names[0] if read_names else "issue") + ']}"'
    )
    description_expr = (
        _template_expression(description_var["samples"][0], readable)
        if description_var and description_var.get("samples")
        else summary_expr
    )

    guard = str(guards.get("requires_approval_if") or "")
    # A constant observed on every run becomes the priority sent, read from the
    # page when the browser half saw it and hard-set only when it did not.
    priority_expr = (
        "values[" + literal(guard_field) + "]"
        if guard_field and guard_field in read_names
        else literal(str(guard_constant["value"]) if guard_constant else "High")
    )

    variable_doc = "\n".join(
        f"    {v['placeholder']:<18} e.g. {', '.join(str(x) for x in v.get('samples', [])[:2])}"
        for v in variables
    ) or "    (none observed)"

    irreversible = sorted(str(i) for i in (guards.get("irreversible") or []))
    header = _HEADER.format(
        name=name,
        cluster_id=cluster_id,
        description=description,
        filename=filename,
        browser_connectors=", ".join(browser_connectors),
        api_connectors=", ".join(api_connectors),
        occurrences=occurrences,
        variable_doc=variable_doc,
        start_url="TODO: the portal URL",
        selectors=_selector_table(selectors),
        irreversible=("{" + ", ".join(literal(i) for i in irreversible) + "}")
        if irreversible
        else "set()",
        guard=guard,
    )

    source = (
        header
        + _PHASE_ONE.format(reads=reads)
        + _PHASE_TWO.format(
            summary_template=summary_expr,
            description_template=description_expr,
            priority_expression=priority_expr,
        )
        + _MAIN.format(
            name=name,
            browser_connectors=", ".join(browser_connectors),
            api_connectors=", ".join(api_connectors),
        )
    )

    caveats = []
    if selectors:
        caveats.append(
            f"{len(selectors)} selector(s) and the portal URL are placeholders. The "
            "activity log records that a control was read, not how to locate it. The "
            "script refuses to run on a placeholder rather than reading the wrong field."
        )
    caveats.append(
        f"Phase 2 writes to {', '.join(api_connectors)} only with --yes; without it the "
        "payload is printed and nothing is created."
    )
    _ = by_name, browser_steps  # kept for readability of the mapping above

    return GeneratedCode(
        method="hybrid",
        filename=filename,
        source=source,
        requirements=[
            "pip install playwright && playwright install chromium",
            "LOOP_PORTAL_URL, or edit START_URL.",
            "LOOP_JIRA_SITE_URL, LOOP_JIRA_EMAIL, LOOP_JIRA_API_TOKEN, LOOP_JIRA_PROJECT.",
            "SELECTORS filled in from the live portal.",
        ],
        caveats=caveats,
    )
