"""Generate a Playwright script for a flow that has to be driven through a UI.

Chosen only when a step touches a system with no usable API, because clicking
through a browser is slower and more brittle than calling one. When that is the
only way in, it is the only way in.

The honest limit of this generator, stated in the file it writes: an activity
log records *that* a control was used, not the selector that would find it
again. Field names survive collection and are used where they exist; everything
else is emitted as a named entry in one SELECTORS table at the top of the file,
so making the script real is filling in a short table against the live UI rather
than reverse-engineering generated code. Inventing selectors that look right and
match nothing would be worse than leaving the table visible.
"""

from __future__ import annotations

from typing import Any

from app.services.codegen.base import GeneratedCode, identifier, literal

_HEADER = '''#!/usr/bin/env python3
"""{name}

Generated by LOOP from cluster {cluster_id}.
{description}

    pip install playwright && playwright install chromium
    python3 {filename}                # dry run, opens nothing, prints the plan
    python3 {filename} --yes          # drive the browser for real
    python3 {filename} --yes --headed # ...and watch it happen

Before the first real run, fill in SELECTORS below. The activity log recorded
which controls were used, not how to find them again, so those are the one
thing that cannot be generated from observation.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys

from playwright.async_api import TimeoutError as PlaywrightTimeout
from playwright.async_api import async_playwright

#: Where each step starts. Set these to the real URLs.
START_URLS = {start_urls}

#: How to find each control. One entry per step that touches the page.
#:
#: Prefer a role-based locator over a CSS path: `get_by_role("button",
#: name="Save")` survives a redesign that `div.x7 > button:nth-child(3)` does
#: not, and this script is meant to keep working.
SELECTORS = {selectors}

#: Steps whose effect cannot be undone. Held when GUARD matches.
IRREVERSIBLE = {irreversible}
GUARD = {guard!r}

#: How long to wait for a control before giving up, in milliseconds. A UI
#: automation that hangs forever is worse than one that fails.
TIMEOUT_MS = int(os.environ.get("LOOP_PLAYWRIGHT_TIMEOUT_MS", "15000"))


class StepFailed(RuntimeError):
    """A step could not complete."""


class NeedsApproval(RuntimeError):
    """The guard matched on an irreversible step."""


class NotConfigured(RuntimeError):
    """A selector or URL was left as a placeholder."""


_CONDITION = re.compile(r"^\\s*([A-Za-z_][A-Za-z0-9_. ]*?)\\s*(>=|<=|==|!=|>|<)\\s*(.+?)\\s*$")


def _coerce(raw):
    text = raw.strip().strip("'\\"")
    for caster in (int, float):
        try:
            return caster(text)
        except ValueError:
            pass
    if text.lower() in ("true", "false"):
        return text.lower() == "true"
    return text


def guard_matches(expression, values):
    """True when the guard holds. Fails closed on anything unparseable."""
    if not expression:
        return False
    match = _CONDITION.match(expression)
    if not match:
        return False
    name, operator, raw = match.groups()
    key = name.strip()
    if key not in values:
        key = key.split(".")[-1]
    if key not in values:
        return False
    left, right = values[key], _coerce(raw)
    try:
        return {{
            ">": left > right, "<": left < right,
            ">=": left >= right, "<=": left <= right,
            "==": left == right, "!=": left != right,
        }}[operator]
    except TypeError:
        return False


def _selector(step_id):
    """The selector for a step, refusing to run on a placeholder."""
    value = SELECTORS.get(step_id, "")
    if not value or value.startswith("TODO"):
        raise NotConfigured(
            "SELECTORS[{{!r}}] is still a placeholder. Fill it in from the live "
            "page before running with --yes.".format(step_id)
        )
    return value


def _url(step_id):
    value = START_URLS.get(step_id, "")
    if not value or value.startswith("TODO"):
        raise NotConfigured(
            "START_URLS[{{!r}}] is still a placeholder.".format(step_id)
        )
    return value
'''

_MAIN = '''

STEPS = [
{step_table}
]


async def run(page, trigger, apply_changes):
    """Drive every step in order against one page."""
    values = dict(trigger)
    for step_id, label, handler in STEPS:
        if step_id in IRREVERSIBLE and guard_matches(GUARD, values):
            raise NeedsApproval(
                "guard held {{}} ({{}}): {{}}".format(step_id, label, GUARD)
            )
        produced = await handler(page, values, apply_changes)
        if produced:
            values.update(produced)
        print("  {{:<4}} {{:<34}} ok".format(step_id, label))
    return values


async def main_async(args):
    if not args.yes:
        print("DRY RUN — no browser is opened. The plan is:\\n")
        for step_id, label, _ in STEPS:
            held = " (held by guard when it matches)" if step_id in IRREVERSIBLE else ""
            print("  {{:<4}} {{}}{{}}".format(step_id, label, held))
        print("\\nRe-run with --yes to drive the browser.")
        return 0

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=not args.headed)
        context = await browser.new_context()
        page = await context.new_page()
        page.set_default_timeout(TIMEOUT_MS)
        try:
            await run(page, {{}}, args.yes)
            print("\\ncompleted")
            return 0
        except NeedsApproval as exc:
            print("\\nheld for approval: {{}}".format(exc))
            return 0
        except (StepFailed, NotConfigured, PlaywrightTimeout) as exc:
            print("\\nfailed: {{}}".format(exc), file=sys.stderr)
            return 1
        finally:
            await context.close()
            await browser.close()


def main():
    parser = argparse.ArgumentParser(description={name!r})
    parser.add_argument("--yes", action="store_true", help="actually drive the browser")
    parser.add_argument("--headed", action="store_true", help="show the browser window")
    return asyncio.run(main_async(parser.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _navigate(func: str, step_id: str, step: dict[str, Any]) -> str:
    return f'''

async def {func}(page, values, apply_changes):
    """{step.get("description") or "navigate"}"""
    await page.goto(_url({literal(step_id)}), wait_until="domcontentloaded")
    return {{"page_url": page.url}}
'''


def _click(func: str, step_id: str, step: dict[str, Any]) -> str:
    return f'''

async def {func}(page, values, apply_changes):
    """{step.get("description") or "click a control"}"""
    target = page.locator(_selector({literal(step_id)}))
    if not apply_changes:
        print("      would click {{}}".format(_selector({literal(step_id)})))
        return {{}}
    await target.click()
    await page.wait_for_load_state("networkidle")
    return {{}}
'''


def _fill(func: str, step_id: str, step: dict[str, Any], fields: list[str]) -> str:
    """A step that types into fields. Field names came from the collector."""
    assignments = "\n".join(
        f'''    value = values.get({literal(name)})
    if value is not None:
        await page.locator(_selector({literal(step_id)})).fill(str(value))'''
        for name in fields[:1]
    ) or "    pass"
    return f'''

async def {func}(page, values, apply_changes):
    """{step.get("description") or "fill in the form"}

    Fields observed on this step: {", ".join(fields) or "none recorded"}.
    """
    if not apply_changes:
        print("      would fill {", ".join(fields) or "the form"}")
        return {{}}
{assignments}
    return {{}}
'''


def _read(func: str, step_id: str, step: dict[str, Any], fields: list[str]) -> str:
    return f'''

async def {func}(page, values, apply_changes):
    """{step.get("description") or "read values off the page"}

    Reads the text of the located element. Which of {fields or ["the page"]} it
    maps to depends on the page, so confirm the mapping once against the real UI.
    """
    text = await page.locator(_selector({literal(step_id)})).inner_text()
    return {{{literal(fields[0] if fields else "page_text")}: text.strip()}}
'''


def generate(
    *,
    name: str,
    description: str,
    cluster_id: str,
    steps: list[dict[str, Any]],
    guards: dict[str, Any],
) -> GeneratedCode:
    """Emit a Playwright script for a flow definition."""
    filename = f"{identifier(name, 'automation')}_browser.py"
    irreversible = sorted(str(s) for s in (guards.get("irreversible") or []))
    guard = str(guards.get("requires_approval_if") or "")

    bodies: list[str] = []
    table: list[str] = []
    selectors: dict[str, str] = {}
    start_urls: dict[str, str] = {}
    caveats: list[str] = []

    for index, step in enumerate(steps, start=1):
        step_id = str(step.get("id") or f"s{index}")
        connector = str(step.get("connector") or "browser")
        action = str(step.get("type") or "read")
        fields = [str(f) for f in (step.get("outputs") or [])]
        func = f"step_{identifier(step_id)}_{identifier(action)}"
        label = f"{connector}:{action}"

        if action == "navigate":
            bodies.append(_navigate(func, step_id, step))
            start_urls[step_id] = f"TODO: the URL where {step_id} starts"
        elif action in ("create", "update", "send"):
            bodies.append(_fill(func, step_id, step, fields))
            selectors[step_id] = f"TODO: the field to type into for {step_id}"
        elif action in ("read", "extract", "search"):
            bodies.append(_read(func, step_id, step, fields))
            selectors[step_id] = f"TODO: the element holding {fields[0] if fields else 'the value'}"
        else:
            bodies.append(_click(func, step_id, step))
            selectors[step_id] = f"TODO: the control clicked at {step_id}"

        table.append(f"    ({literal(step_id)}, {literal(label)}, {func}),")

    placeholders = len(selectors) + len(start_urls)
    if placeholders:
        caveats.append(
            f"{placeholders} selector(s)/URL(s) are placeholders. The activity log "
            "records that a control was used, not how to locate it, so these are "
            "filled in once against the live UI. The script refuses to run on a "
            "placeholder rather than clicking the wrong thing."
        )

    def _table(mapping: dict[str, str]) -> str:
        if not mapping:
            return "{}"
        rows = "\n".join(f"    {literal(k)}: {literal(v)}," for k, v in mapping.items())
        return "{\n" + rows + "\n}"

    header = _HEADER.format(
        name=name,
        cluster_id=cluster_id,
        description=description,
        filename=filename,
        start_urls=_table(start_urls),
        selectors=_table(selectors),
        irreversible=("{" + ", ".join(literal(i) for i in irreversible) + "}")
        if irreversible
        else "set()",
        guard=guard,
    )
    source = header + "".join(bodies) + _MAIN.format(
        step_table="\n".join(table), name=name
    )

    return GeneratedCode(
        method="playwright",
        filename=filename,
        source=source,
        requirements=[
            "pip install playwright && playwright install chromium",
            "Sign-in state for the target system, or a login step added by hand.",
            "SELECTORS and START_URLS filled in from the live UI.",
        ],
        caveats=caveats,
    )
