"""Generate a standalone Python script that runs a flow definition.

The script is deliberately dependency-free and imports nothing from Kriyā AI: the
point of handing someone a file is that they can read it, run it, and keep it
when Kriyā AI is not around. It re-implements the two things the engine does that
matter for correctness — resolving each step's inputs from what earlier steps
produced, and holding an irreversible step behind the guard — because a script
that skips those is not the automation that was reviewed.

Steps the generator cannot implement honestly raise on the spot, naming the
credential or the API they need. That is worse to look at than a plausible stub
and far better to run, because it fails at generation-time reading rather than
silently at 3am having done half a job.
"""

from __future__ import annotations

from typing import Any

from app.services.codegen.base import GeneratedCode, identifier, literal

#: Connectors this generator can implement fully, with no credentials.
_LOCAL = {"files", "pdf"}

_HEADER = '''#!/usr/bin/env python3
"""{name}

Generated by Kriyā AI from cluster {cluster_id}.
{description}

This script is standalone: standard library only, no Kriyā AI imports.

    python3 {filename}              # dry run, prints the plan, changes nothing
    python3 {filename} --yes        # actually do it

Everything it touches is confined to LOOP_FILES_ROOT ({files_root} by default).
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import zlib
{extra_imports}from pathlib import Path

ROOT = Path(os.environ.get("LOOP_FILES_ROOT", {files_root!r})).expanduser().resolve()

#: Steps whose effect cannot be undone. Checked against GUARD before running.
IRREVERSIBLE = {irreversible}
#: The hold Kriyā AI measured. An irreversible step does not run when this is true.
GUARD = {guard!r}


class StepFailed(RuntimeError):
    """A step could not complete. Stops the run, as the engine does."""


class NeedsApproval(RuntimeError):
    """The guard matched on an irreversible step. A human decides from here."""


# ── guard evaluation ────────────────────────────────────────────────────────
# Field-versus-literal comparison only, mirroring the restricted comparator the
# engine uses. eval() is not used here for the same reason it is not used there:
# the flow definition this was generated from is partly model-written.

_CONDITION = re.compile(r"^\\s*([A-Za-z_][A-Za-z0-9_. ]*?)\\s*(>=|<=|==|!=|>|<)\\s*(.+?)\\s*$")


def _coerce(raw):
    text = raw.strip().strip("'\\"")
    for caster in (int, float):
        try:
            return caster(text)
        except ValueError:
            pass
    if text.lower() in ("true", "false"):
        return text.lower() == "true"
    return text


def guard_matches(expression, values):
    """True when the guard holds. Unparseable or unknown fields fail closed."""
    if not expression:
        return False
    match = _CONDITION.match(expression)
    if not match:
        return False
    name, operator, raw = match.groups()
    key = name.strip()
    if key not in values:
        key = key.split(".")[-1]
    if key not in values:
        return False
    left, right = values[key], _coerce(raw)
    try:
        return {{
            ">": left > right, "<": left < right,
            ">=": left >= right, "<=": left <= right,
            "==": left == right, "!=": left != right,
        }}[operator]
    except TypeError:
        return False


def _inside_root(path):
    """Refuse to touch anything outside ROOT, as the files connector does."""
    try:
        path.resolve().relative_to(ROOT)
    except ValueError:
        return False
    return True


def _resolve(values, *names):
    for name in names:
        value = values.get(name)
        if value not in (None, ""):
            return value
    return None
'''

_PDF_HELPERS = '''

# ── PDF text, standard library only ─────────────────────────────────────────
# A one-page invoice keeps its text in content streams as `(...) Tj` operators,
# usually behind Flate compression, which zlib already handles. That is the
# whole reason this script needs nothing installed.

_STREAM = re.compile(rb"stream\\r?\\n(.*?)\\r?\\nendstream", re.S)
_SHOW_TEXT = re.compile(r"\\((?:\\\\.|[^\\\\()])*\\)\\s*Tj", re.S)
_ESCAPES = {"n": "\\n", "r": "\\r", "t": "\\t", "b": "\\b", "f": "\\f"}


def pdf_text(path):
    """Every visible string in a PDF, in document order."""
    raw = Path(path).read_bytes()
    out = []
    for chunk in _STREAM.findall(raw):
        try:
            body = zlib.decompress(chunk)
        except zlib.error:
            body = chunk
        text = body.decode("latin-1", "replace")
        for token in _SHOW_TEXT.findall(text):
            inner = token[token.index("(") + 1 : token.rindex(")")]
            result, index = [], 0
            while index < len(inner):
                char = inner[index]
                if char == "\\\\" and index + 1 < len(inner):
                    nxt = inner[index + 1]
                    result.append(_ESCAPES.get(nxt, nxt))
                    index += 2
                    continue
                result.append(char)
                index += 1
            out.append("".join(result))
    return "\\n".join(out)


_AMOUNT = re.compile(
    r"(?:total\\s+due|grand\\s+total|amount\\s+due|total)\\D{0,20}?([0-9][0-9,]*\\.?[0-9]{0,2})",
    re.I,
)
_INVOICE_NO = re.compile(r"invoice\\s*(?:number|no\\.?|#)\\s*[:\\-]?\\s*([A-Za-z0-9\\-/]+)", re.I)
_DATE = re.compile(r"invoice\\s*date\\s*[:\\-]?\\s*(\\d{4}-\\d{2}-\\d{2})", re.I)
_ACCOUNT = re.compile(r"account\\s*[:\\-]?\\s*([0-9\\-]{8,})", re.I)


def parse_invoice(text):
    """Pull the billing fields out of extracted invoice text.

    `amount` comes back in minor units (paise) as an integer, never a float —
    money in a float is a rounding bug with a delay on it.
    """
    found = {}
    # The issuer is the letterhead: the first non-empty line of the document.
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            found["vendor"] = stripped.title() if stripped.isupper() else stripped
            break
    match = _AMOUNT.search(text)
    if match:
        found["amount"] = int(round(float(match.group(1).replace(",", "")) * 100))
    for key, pattern in (
        ("invoice_no", _INVOICE_NO), ("invoice_date", _DATE), ("account_id", _ACCOUNT)
    ):
        hit = pattern.search(text)
        if hit:
            found[key] = hit.group(1).strip()
    return found
'''

_MAIN = '''

# ── the flow ────────────────────────────────────────────────────────────────

STEPS = [
{step_table}
]


def run(trigger, apply_changes):
    """Run every step in order, stopping at the first failure.

    `trigger` is what the arriving item carries. Returns the resolved values.
    """
    values = dict(trigger)
    for step_id, label, handler in STEPS:
        if step_id in IRREVERSIBLE and guard_matches(GUARD, values):
            raise NeedsApproval(
                "guard held {{}} ({{}}): {{}}".format(step_id, label, GUARD)
            )
        produced = handler(values, apply_changes)
        if produced:
            values.update(produced)
        print("  {{:<4}} {{:<34}} ok".format(step_id, label))
    return values


def main():
    parser = argparse.ArgumentParser(description={name!r})
    parser.add_argument("--yes", action="store_true", help="actually make changes")
    parser.add_argument("--source", help="the file to process; defaults to the whole inbox")
    args = parser.parse_args()

    if not ROOT.is_dir():
        print("no such directory: {{}}".format(ROOT), file=sys.stderr)
        print("set LOOP_FILES_ROOT, or create it.", file=sys.stderr)
        return 1

    inbox = ROOT / "Inbox"
    if args.source:
        candidates = [Path(args.source)]
    elif inbox.is_dir():
        candidates = sorted(p for p in inbox.iterdir() if p.is_file())
    else:
        candidates = []

    if not candidates:
        print("nothing to do: {{}} is empty.".format(inbox))
        return 0

    if not args.yes:
        print("DRY RUN — nothing will be changed. Re-run with --yes to apply.\\n")

    held, done, failed = [], 0, 0
    for path in candidates:
        print("{{}}".format(path.name))
        try:
            run({{"source_path": str(path), "filename": path.name}}, args.yes)
            done += 1
        except NeedsApproval as exc:
            print("  held for approval: {{}}".format(exc))
            held.append(path.name)
        except StepFailed as exc:
            print("  failed: {{}}".format(exc), file=sys.stderr)
            failed += 1
        print()

    print("{{}} completed, {{}} held for approval, {{}} failed".format(done, len(held), failed))
    for name in held:
        print("  held: {{}}".format(name))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _files_read(func: str, step: dict[str, Any]) -> str:
    return f'''

def {func}(values, apply_changes):
    """{step.get("description") or "read a file"}"""
    name = _resolve(values, "source_path", "path", "filename", "file")
    if not name:
        raise StepFailed("no source file for this step")
    path = Path(name).expanduser()
    if not path.is_absolute():
        path = ROOT / path
    if not _inside_root(path):
        raise StepFailed("{{}} is outside {{}}; refusing to touch it".format(path, ROOT))
    if not path.is_file():
        raise StepFailed("no such file: {{}}".format(path))
    return {{
        "source_path": str(path.resolve()),
        "filename": path.name,
        "size_bytes": path.stat().st_size,
    }}
'''


def _pdf_extract(func: str, step: dict[str, Any]) -> str:
    return f'''

def {func}(values, apply_changes):
    """{step.get("description") or "extract fields from the document"}"""
    source = _resolve(values, "source_path", "path", "filename")
    if not source:
        raise StepFailed("nothing to extract from: no source_path resolved")
    path = Path(source)
    if not path.is_absolute():
        path = ROOT / path
    if not path.is_file():
        raise StepFailed("no such file: {{}}".format(path))
    fields = parse_invoice(pdf_text(path))
    if not fields:
        raise StepFailed("no billing fields found in {{}}".format(path.name))
    return fields
'''


def _files_create(func: str, step: dict[str, Any]) -> str:
    return f'''

def {func}(values, apply_changes):
    """{step.get("description") or "file the document away"}"""
    source = _resolve(values, "source_path", "path")
    if not source:
        raise StepFailed("no source file to file away")
    path = Path(source)
    if not path.is_file():
        raise StepFailed("no such file: {{}}".format(path))

    date = str(_resolve(values, "invoice_date", "billing_period") or "")
    year, month = (date[:4], date[5:7]) if len(date) >= 7 else ("Undated", "")
    vendor = str(_resolve(values, "vendor", "supplier") or "Unfiled")
    vendor = re.sub(r"[^A-Za-z0-9 ._-]+", "", vendor).strip() or "Unfiled"

    target_dir = ROOT / "Filed" / vendor / year / month
    target = target_dir / path.name
    if not _inside_root(target):
        raise StepFailed("refusing to write outside {{}}".format(ROOT))

    if not apply_changes:
        print("      would file -> {{}}".format(target))
        return {{"filed_path": str(target), "applied": False}}

    target_dir.mkdir(parents=True, exist_ok=True)
    final, counter = target, 1
    while final.exists():
        final = target_dir / "{{}}-{{}}{{}}".format(target.stem, counter, target.suffix)
        counter += 1
    shutil.move(str(path), str(final))
    return {{"filed_path": str(final), "applied": True}}
'''


def _jira_send(func: str, step: dict[str, Any]) -> str:
    return f'''

def {func}(values, apply_changes):
    """{step.get("description") or "comment on the tracking issue"}

    Jira Cloud REST v3, over the standard library. Credentials come from the
    environment and are never written into this file.
    """
    site = os.environ.get("LOOP_JIRA_SITE_URL", "").strip().rstrip("/")
    email = os.environ.get("LOOP_JIRA_EMAIL", "").strip()
    token = os.environ.get("LOOP_JIRA_API_TOKEN", "").strip()
    missing = [n for n, v in (
        ("LOOP_JIRA_SITE_URL", site), ("LOOP_JIRA_EMAIL", email),
        ("LOOP_JIRA_API_TOKEN", token),
    ) if not v]
    if missing:
        raise StepFailed(
            "cannot comment on Jira: set {{}}".format(", ".join(missing))
        )

    key = _resolve(values, "ticket_id", "issue_key", "key")
    if not key:
        raise StepFailed("no Jira issue to comment on")

    amount = values.get("amount")
    note = "Filed {{}} for {{}}{{}}.".format(
        values.get("invoice_no") or values.get("filename") or "invoice",
        values.get("vendor") or "vendor",
        "" if amount is None else " — INR {{:,.2f}}".format(amount / 100),
    )

    if not apply_changes:
        print("      would comment on {{}}: {{}}".format(key, note))
        return {{"comment_preview": note, "applied": False}}

    body = json.dumps({{
        "body": {{
            "type": "doc", "version": 1,
            "content": [{{"type": "paragraph",
                         "content": [{{"type": "text", "text": note}}]}}],
        }}
    }}).encode()
    credentials = base64.b64encode("{{}}:{{}}".format(email, token).encode()).decode()
    request = urllib.request.Request(
        "{{}}/rest/api/3/issue/{{}}/comment".format(site, key),
        data=body,
        method="POST",
        headers={{
            "Authorization": "Basic {{}}".format(credentials),
            "Content-Type": "application/json",
            "Accept": "application/json",
        }},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            created = json.load(response)
    except urllib.error.HTTPError as exc:
        raise StepFailed(
            "Jira rejected the comment on {{}}: {{}} {{}}".format(
                key, exc.code, exc.read().decode("utf-8", "replace")[:200]
            )
        ) from exc
    except urllib.error.URLError as exc:
        raise StepFailed("could not reach Jira: {{}}".format(exc.reason)) from exc
    return {{"comment_id": str(created.get("id") or ""), "applied": True}}
'''


def _unimplemented(func: str, step: dict[str, Any], reason: str) -> str:
    connector = step.get("connector")
    return f'''

def {func}(values, apply_changes):
    """{step.get("description") or f"{step.get('type')} via {connector}"}

    Not generated. {reason}
    """
    raise StepFailed(
        {literal(f"step {step.get('id')} needs the {connector} connector: {reason}")}
    )
'''


#: Credentials each API connector would need, so an ungenerated step says
#: exactly what is missing rather than "not implemented".
_CREDENTIALS = {
    "gmail": "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET (Gmail API v1)",
    "outlook": "MS_CLIENT_ID, MS_CLIENT_SECRET and MS_TENANT_ID (Microsoft Graph)",
    "sheets": "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET (Sheets API v4)",
    "drive": "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET (Drive API v3)",
    "slack": "SLACK_BOT_TOKEN (chat.postMessage)",
    "jira": "LOOP_JIRA_SITE_URL, LOOP_JIRA_EMAIL and LOOP_JIRA_API_TOKEN (REST v3)",
    "erp": "ERP_BASE_URL and ERP_API_TOKEN",
    "crm": "the tenant CRM API credentials",
}


def generate(
    *,
    name: str,
    description: str,
    cluster_id: str,
    steps: list[dict[str, Any]],
    guards: dict[str, Any],
    files_root: str,
) -> GeneratedCode:
    """Emit a runnable Python script for a flow definition."""
    filename = f"{identifier(name, 'automation')}.py"
    irreversible = sorted(str(s) for s in (guards.get("irreversible") or []))
    guard = str(guards.get("requires_approval_if") or "")

    bodies: list[str] = []
    table: list[str] = []
    caveats: list[str] = []
    needs_pdf = False
    needs_network = False

    for index, step in enumerate(steps, start=1):
        step_id = str(step.get("id") or f"s{index}")
        connector = str(step.get("connector") or "browser")
        action = str(step.get("type") or "read")
        func = f"step_{identifier(step_id)}_{identifier(connector)}_{identifier(action)}"
        label = f"{connector}:{action}"

        if connector == "files" and action in ("read", "search"):
            bodies.append(_files_read(func, step))
        elif connector == "pdf" and action in ("extract", "read"):
            bodies.append(_pdf_extract(func, step))
            needs_pdf = True
        elif connector == "files" and action in ("create", "update"):
            bodies.append(_files_create(func, step))
        elif connector == "jira" and action in ("send", "create"):
            bodies.append(_jira_send(func, step))
            needs_network = True
            caveats.append(
                f"{step_id} ({label}) posts to Jira for real. It needs "
                "LOOP_JIRA_SITE_URL, LOOP_JIRA_EMAIL and LOOP_JIRA_API_TOKEN, "
                "and stops with a precise error when they are unset."
            )
        else:
            reason = _CREDENTIALS.get(
                connector, f"no generator covers {connector}:{action} yet"
            )
            bodies.append(_unimplemented(func, step, reason))
            caveats.append(
                f"{step_id} ({label}) is not implemented: it needs {reason}. "
                "The script stops there rather than pretending it succeeded."
            )

        table.append(f"    ({literal(step_id)}, {literal(label)}, {func}),")

    extra_imports = (
        "import base64\nimport json\nimport urllib.error\nimport urllib.request\n"
        if needs_network
        else ""
    )
    header = _HEADER.format(
        extra_imports=extra_imports,
        name=name,
        cluster_id=cluster_id,
        description=description,
        filename=filename,
        files_root=files_root,
        irreversible=("{" + ", ".join(literal(i) for i in irreversible) + "}")
        if irreversible
        else "set()",
        guard=guard,
    )
    source = header
    if needs_pdf:
        source += _PDF_HELPERS
    source += "".join(bodies)
    source += _MAIN.format(step_table="\n".join(table), name=name)

    requirements = [
        "Python 3.11 or newer. No packages to install — standard library only.",
        f"LOOP_FILES_ROOT pointing at the document root (default {files_root}).",
    ]
    if guard:
        requirements.append(
            f"A person to review anything held by the guard `{guard}`."
        )

    return GeneratedCode(
        method="python",
        filename=filename,
        source=source,
        requirements=requirements,
        caveats=caveats,
    )
